version: "3.8"

services:
  singlestore:
    image: "memsql/cluster-in-a-box"
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${SINGLESTORE_LICENSE_KEY}
      ROOT_PASSWORD: ${SINGLESTORE_PASSWORD}
      START_AFTER_INIT: "Y"

  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq/log

volumes:
  rabbitmq-data:
  rabbitmq-logs: