apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gauchoracing/mp_auth:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_ENDPOINT
              value: "http://auth:8080"
            - name: SERVICE_HEALTH_CHECK
              value: "http://auth:8080/auth/ping"
            - name: RINCON_USER
              value: "admin"
            - name: RINCON_PASSWORD
              value: "admin"
            - name: RINCON_ENDPOINT
              value: "http://rincon:10311"
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: sentinel-config
