apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/gaucho-racing/mapache/auth:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /auth/ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /auth/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          env:
            - name: PORT
              value: "8080"
            - name: KERBECS_ENDPOINT
              value: "http://kerbecs:10300"
            - name: KERBECS_USER
              value: "admin"
            - name: KERBECS_PASSWORD
              value: "admin"
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: sentinel-config
