apiVersion: v1
kind: Service
metadata:
  name: kerbecs
spec:
  type: LoadBalancer
  selector:
    app: kerbecs
  ports:
    - name: admin
      protocol: TCP
      port: 10300
      targetPort: 10300
    - name: api
      protocol: TCP
      port: 10310
      targetPort: 10310
