apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerbecs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerbecs
  template:
    metadata:
      labels:
        app: kerbecs
    spec:
      containers:
        - name: kerbecs
          image: bk1031/kerbecs:latest
          ports:
            - containerPort: 10300
              protocol: TCP
            - containerPort: 10310
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /admin-gw/ping
              port: 10300
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /admin-gw/ping
              port: 10300
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          env:
            - name: ENV
              value: "PROD"
            - name: KERBECS_CONFIG
              value: /etc/kerbecs/kerbecs.yaml
            - name: KERBECS_USER
              value: "admin"
            - name: KERBECS_PASSWORD
              value: "admin"
          volumeMounts:
            - name: kerbecs-config
              mountPath: /etc/kerbecs
              readOnly: true
      volumes:
        - name: kerbecs-config
          configMap:
            name: kerbecs-config
