apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: gauchoracing/mp_query:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /query/ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /query/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          env:
            - name: PORT
              value: "8080"
            - name: KERBECS_ENDPOINT
              value: "http://kerbecs:10300"
            - name: KERBECS_USER
              value: "admin"
            - name: KERBECS_PASSWORD
              value: "admin"
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: sentinel-config
