[project]
name = "query"
version = "0.1.0"
description = ""
authors = [
    {name = "Bharat Kathi",email = "bkathi@ucsb.edu"},
    {name = "Jacob Jurek", email = "jacobjurek@ucsb.edu"},
    {name = "Madhav Viswesvaran", email = "madhav@ucsb.edu"},
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.115.10,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "sqlalchemy (>=2.0.38,<3.0.0)",
    "pymysql (>=1.1.1,<2.0.0)",
    "numpy (>=2.2.3,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
query = "query.main:main"