name: build
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
  auth:
    runs-on: ubuntu-latest
    name: auth
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Build Auth
        run: |
          cd auth
          go get .
          go build

  dashboard:
    runs-on: ubuntu-latest
    name: dashboard
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Build Dashboard
        run: |
          cd dashboard
          npm ci
          npm run build

  jeddah:
    runs-on: ubuntu-latest
    name: jeddah
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Build Jeddah
        run: |
          cd jeddah
          go get .
          go build

  gr24:
    runs-on: ubuntu-latest
    name: gr24
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Build GR24
        run: |
          cd gr24
          go get .
          go build

  gr25:
    runs-on: ubuntu-latest
    name: gr25
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Build GR25
        run: |
          cd gr25
          go get .
          go build

  query:
    runs-on: ubuntu-latest
    name: query
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.0
      - name: Build Query
        run: |
          cd query
          poetry install
          poetry build

  all:
    needs: [auth, dashboard, jeddah, gr24, gr25, query]
    runs-on: ubuntu-latest
    name: all
    steps:
      - name: Build All
        run: echo "All builds completed successfully!"
