name: build
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
    dashboard:
        runs-on: ubuntu-latest
        name: Dashboard Build
        steps:
          - uses: actions/checkout@v4
            with:
              submodules: true
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
                node-version: '22.x'
          - name: Build Dashboard
            run: |
              cd dashboard
              npm ci
              npm run build

    auth:
        runs-on: ubuntu-latest
        name: auth
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              submodules: true
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.22.0'
          - name: Build Auth
            run: |
              cd auth
              go get .
              go build

    jeddah:
        runs-on: ubuntu-latest
        name: jeddah
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              submodules: true
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.22.0'
          - name: Build Jeddah
            run: |
              cd jeddah
              go get .
              go build

    gr24:
        runs-on: ubuntu-latest
        name: gr24
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              submodules: true
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.22.0'
          - name: Build GR24
            run: |
              cd gr24
              go get .
              go build

    all:
        needs: [dashboard, auth, jeddah, gr24]
        runs-on: ubuntu-latest
        name: all
        steps:
          - name: Build All
            run: echo "All builds completed successfully!"