name: Mapache Tests
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }} by @${{ github.actor }}

on: [push]

jobs:
  rigby_test_job:
    runs-on: ubuntu-latest
    name: Test Rigby
    defaults:
      run:
        working-directory: ./rigby
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10.10'
      - name: Install poetry
        run: |
            python -m pip install poetry
      - name: Configure poetry
        run: |
            python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
            python -m poetry install
      - name: Run tests
        run: |
            python -m poetry run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./rigby/coverage.lcov
          verbose: true

  ingest_test_job:
    runs-on: ubuntu-latest
    name: Test Ingest
    defaults:
      run:
        working-directory: ./ingest
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'
      - name: Install dependencies
        run: |
            go get .
      - name: Run tests
        run: |
            sh scripts/test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./ingest/coverage.out
          verbose: true